### ISSUE TITLE
erorr in FF's Main.hs

### ISSUE THREAD

**Issue by dylanmc** [elliottt/story#1]
Latest commit won't build, with this error:

example/Main.hs:8:19:
    Module ‘FF.Input’ does not export ‘parseDomain’

Is this because I shouldn't "cabal install", but rather use runhaskell or ghci?

**Comment by elliottt** [comment]
I've been working in ghci, loading in that test file I sent you a while
back.  I just finished a bunch of stuff though, so it's probably time to
send you a new test file :)

**Comment by elliottt** [comment]
Well, I think that this issue is probably not too relevant anymore, as I've re-started development from a clean slate :)

I have added an executable that builds and will output grounded domain/problem combinations though, which is a start on the road to actually processing interesting problems!
